/// <reference types="vite/client" />

/**
 * @fileoverview Mocks the @/.source module for testing.
 *
 * The `@/.source` module should be generated by fumadocs mdx plugin, but this
 * plugin doesn't work in browser-test environment.
 *
 * This is a direct copy of <root>/.source/index.ts, when fumadocs is updated, should check if the mock is still valid.
 */

import { fromConfig } from "fumadocs-mdx/runtime/vite";
import type * as Config from "../../source.config";

export const create = fromConfig<typeof Config>();

export const docs = {
  doc: create.doc(
    "docs",
    "content/docs",
    import.meta.glob(["./**/*.{mdx,md}"], {
      query: {
        collection: "docs",
      },
      base: "./../content/docs",
    }),
  ),
  meta: create.meta(
    "docs",
    "content/docs",
    import.meta.glob(["./**/*.{json,yaml}"], {
      import: "default",
      base: "./../content/docs",
      query: {
        collection: "docs",
      },
    }),
  ),
};
